# master1
vrrp_script chk_haproxy {
    script "killall -0 haproxy"
    interval 2
    weight 2
}

vrrp_instance VI_1 {
    state MASTER
    interface ens160                  # ❗确认网卡名（ifconfig 或 ip a）
    virtual_router_id 51            # 同一组 keepalived 必须相同
    priority 100                    # 主节点优先级最高
    advert_int 1
    authentication {
        auth_type PASS
        auth_pass your-ha-pass      # 认证密码，所有节点必须一致
    }
    virtual_ipaddress {
        192.168.10.200/24           # VIP，/24 是子网掩码
    }
    track_script {
        chk_haproxy
    }
}

# 
# master2
vrrp_script chk_haproxy {
    script "killall -0 haproxy"
    interval 2
    weight 2
}

vrrp_instance VI_1 {
    state BACKUP
    interface ens160
    virtual_router_id 51
    priority 90
    advert_int 1
    authentication {
        auth_type PASS
        auth_pass your-ha-pass
    }
    virtual_ipaddress {
        192.168.10.200/24
    }
    track_script {
        chk_haproxy
    }
}

# master3
vrrp_script chk_haproxy {
    script "killall -0 haproxy"
    interval 2
    weight 2
}

vrrp_instance VI_1 {
    state BACKUP
    interface ens160
    virtual_router_id 51
    priority 80
    advert_int 1
    authentication {
        auth_type PASS
        auth_pass your-ha-pass
    }
    virtual_ipaddress {
        192.168.10.200/24
    }
    track_script {
        chk_haproxy
    }
}